import type { Config } from "tailwindcss";
import tailwindcssAnimate from "tailwindcss-animate";

export default {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        rf: {
          "bg": "color-mix(in srgb, var(--rf-bg) calc(<alpha-value> * 100%), transparent)",
          "ink": "color-mix(in srgb, var(--rf-ink) calc(<alpha-value> * 100%), transparent)",
          "ink-soft": "color-mix(in srgb, var(--rf-ink-soft) calc(<alpha-value> * 100%), transparent)",
          "ink-mute": "color-mix(in srgb, var(--rf-ink-mute) calc(<alpha-value> * 100%), transparent)",
          "line": "color-mix(in srgb, var(--rf-line) calc(<alpha-value> * 100%), transparent)",
          "line-soft": "color-mix(in srgb, var(--rf-line-soft) calc(<alpha-value> * 100%), transparent)",
          "card": "color-mix(in srgb, var(--rf-card) calc(<alpha-value> * 100%), transparent)",
          "danger": "color-mix(in srgb, var(--rf-danger) calc(<alpha-value> * 100%), transparent)",
          "danger-soft": "color-mix(in srgb, var(--rf-danger-soft) calc(<alpha-value> * 100%), transparent)",
          "success": "color-mix(in srgb, var(--rf-success) calc(<alpha-value> * 100%), transparent)",
          "success-soft": "color-mix(in srgb, var(--rf-success-soft) calc(<alpha-value> * 100%), transparent)",
          "warn": "color-mix(in srgb, var(--rf-warn) calc(<alpha-value> * 100%), transparent)",
          "warn-soft": "color-mix(in srgb, var(--rf-warn-soft) calc(<alpha-value> * 100%), transparent)",
          "side-bg": "color-mix(in srgb, var(--rf-side-bg) calc(<alpha-value> * 100%), transparent)",
          "side-btn": "color-mix(in srgb, var(--rf-side-btn) calc(<alpha-value> * 100%), transparent)",
          "side-icon": "color-mix(in srgb, var(--rf-side-icon) calc(<alpha-value> * 100%), transparent)",
          "dot": "color-mix(in srgb, var(--rf-dot) calc(<alpha-value> * 100%), transparent)",
          "bubble": "color-mix(in srgb, var(--rf-bubble) calc(<alpha-value> * 100%), transparent)",
          "amber-bg": "color-mix(in srgb, var(--rf-amber-bg) calc(<alpha-value> * 100%), transparent)",
          "amber-ink": "color-mix(in srgb, var(--rf-amber-ink) calc(<alpha-value> * 100%), transparent)",
          "miss-bg": "color-mix(in srgb, var(--rf-miss-bg) calc(<alpha-value> * 100%), transparent)",
          "miss-ink": "color-mix(in srgb, var(--rf-miss-ink) calc(<alpha-value> * 100%), transparent)",
          "online": "color-mix(in srgb, var(--rf-online) calc(<alpha-value> * 100%), transparent)",
          "tint-sage": "color-mix(in srgb, var(--rf-tint-sage) calc(<alpha-value> * 100%), transparent)",
          "tint-blush": "color-mix(in srgb, var(--rf-tint-blush) calc(<alpha-value> * 100%), transparent)",
          "tint-butter": "color-mix(in srgb, var(--rf-tint-butter) calc(<alpha-value> * 100%), transparent)",
          "tint-lavender": "color-mix(in srgb, var(--rf-tint-lavender) calc(<alpha-value> * 100%), transparent)",
          "tint-clay": "color-mix(in srgb, var(--rf-tint-clay) calc(<alpha-value> * 100%), transparent)",
          "tint-sky": "color-mix(in srgb, var(--rf-tint-sky) calc(<alpha-value> * 100%), transparent)",
          "rose": "color-mix(in srgb, var(--rf-rose) calc(<alpha-value> * 100%), transparent)",
          "peach": "color-mix(in srgb, var(--rf-peach) calc(<alpha-value> * 100%), transparent)",
          "cream-bg": "color-mix(in srgb, var(--rf-cream-bg) calc(<alpha-value> * 100%), transparent)",
          "cream-soft": "color-mix(in srgb, var(--rf-cream-soft) calc(<alpha-value> * 100%), transparent)",
          "cream-border": "color-mix(in srgb, var(--rf-cream-border) calc(<alpha-value> * 100%), transparent)",
          "plum-ink": "color-mix(in srgb, var(--rf-plum-ink) calc(<alpha-value> * 100%), transparent)",
          "plum-soft": "color-mix(in srgb, var(--rf-plum-soft) calc(<alpha-value> * 100%), transparent)",
          "h1": "color-mix(in srgb, var(--rf-h1) calc(<alpha-value> * 100%), transparent)",
          "h2": "color-mix(in srgb, var(--rf-h2) calc(<alpha-value> * 100%), transparent)",
          "h3": "color-mix(in srgb, var(--rf-h3) calc(<alpha-value> * 100%), transparent)",
          "h4": "color-mix(in srgb, var(--rf-h4) calc(<alpha-value> * 100%), transparent)",
          "primary": "color-mix(in srgb, var(--rf-primary) calc(<alpha-value> * 100%), transparent)",
          "primary-hover": "color-mix(in srgb, var(--rf-primary-hover) calc(<alpha-value> * 100%), transparent)",
          "on-primary": "color-mix(in srgb, var(--rf-on-primary) calc(<alpha-value> * 100%), transparent)",
        },
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        chart: {
          "1": "hsl(var(--chart-1))",
          "2": "hsl(var(--chart-2))",
          "3": "hsl(var(--chart-3))",
          "4": "hsl(var(--chart-4))",
          "5": "hsl(var(--chart-5))",
        },
      },
      fontFamily: {
        rf: ["var(--font-bricolage)", "ui-sans-serif", "system-ui", "sans-serif"],
        "rf-mono": ["var(--font-geist-mono)", "ui-monospace", "monospace"],
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      backgroundImage: {
        "hero-bg": "url('@/assets/Hero-bg-base-new.avif')",
        "hero-gradient": "var(--hero-gradient)",
        "button-gradient": "var(--button-gradient)",
        // "hero-gradient": "linear-gradient(135deg, #a5a3f7 10%, #ff8650 100%)",
      },
    },
  },
  plugins: [tailwindcssAnimate],
} satisfies Config;
